package com.namakoti.utils;

/**
 * Created by anusha on 12/5/2017.
 */

public enum ServiceMethod {
    LOGIN, REGISTER,CHECKPHONE,PROFILE,EDIT_PROFILE_DETAILS,GET_GOD_NAMES,GET_LANGUAGES,GET_CHANTS,SAVE_CHANT,
    SYNC_CHANT,VERIFY_SMS,UPDATE_PROFILE,UPLOAD_IMAGE,TRANSACTIONS, CAUSE_OPTIONS, GET_GOD_IMAGE,
    KARMIC_SELF,KARMIC_CAUSE_FOR,CREATE_KARMIC_CHANT, ADD_PARTICIPANTS, KARMIC_OTHERS, GET_PARTICIPANTS,
    KARMIC_REQUEST_STATUS, CANCEL_REQUEST,SUBMIT_REQUEST, SEND_REMINDER,TEMPLE_PRINTS, PUSH_TOKEN,
    PUSH_PAYLOAD, SUCCESS_ADD_PART,PANGCHANG, SYNC_KARMIC_CHANT, GET_KARMIC_DETAILS_URL,
}
